config/routes.rb
Rails.application.routes.draw do
  resources :doggies
  resources :parents
  root 'welcome#index'

end

app/models/doggy.rb
class Doggy < ActiveRecord::Base
	belongs_to :parent
	validates :name, presence: true
	validates :breed, presence: true
	validates :age, presence: true
	validates :temperment, presence: true
	validates :funfact, presence: true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	has_many :doggies
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doggies_controller.rb
class DoggiesController < ApplicationController
  before_action :set_doggy, only: [:show, :edit, :update, :destroy]

  # GET /doggies
  # GET /doggies.json
  def index
    @doggies = Doggy.all
  end

  # GET /doggies/1
  # GET /doggies/1.json
  def show
  end

  # GET /doggies/new
  def new
    @doggy = Doggy.new
    @parents = Parent.all
  end

  # GET /doggies/1/edit
  def edit
    @parents = Parent.all
  end

  # POST /doggies
  # POST /doggies.json
  def create
    @doggy = Doggy.new(doggy_params)
    @parents = Parent.all

    respond_to do |format|
      if @doggy.save
        format.html { redirect_to @doggy, notice: 'Doggy was successfully created.' }
        format.json { render :show, status: :created, location: @doggy }
      else
        format.html { render :new }
        format.json { render json: @doggy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doggies/1
  # PATCH/PUT /doggies/1.json
  def update
    respond_to do |format|
      if @doggy.update(doggy_params)
        format.html { redirect_to @doggy, notice: 'Doggy was successfully updated.' }
        format.json { render :show, status: :ok, location: @doggy }
      else
        format.html { render :edit }
        format.json { render json: @doggy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doggies/1
  # DELETE /doggies/1.json
  def destroy
    @doggy.destroy
    respond_to do |format|
      format.html { redirect_to doggies_url, notice: 'Doggy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doggy
      @doggy = Doggy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doggy_params
      params.require(:doggy).permit(:name, :breed, :age, :temperment, :FunFact, :parent_id)
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doggies_helper.rb
module DoggiesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/doggies/_form.html.erb
<%= form_for(@doggy) do |f| %>
  <% if @doggy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doggy.errors.count, "error") %> prohibited this doggy from being saved:</h2>

      <ul>
      <% @doggy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :temperment %><br>
    <%= f.text_field :temperment %>
  </div>
  <div class="field">
    <%= f.label :FunFact %><br>
    <%= f.text_area :FunFact %>
  </div>

  <div class="field">
    <%= f.select(:parent_id, @parents.collect {|a| [ a.name, a.id ] }, {:include_blank => 'Please select a parent'}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doggies/edit.html.erb
<h1>Editing Doggy</h1>

<%= render 'form' %>

<%= link_to 'Show', @doggy %> |
<%= link_to 'Back', doggies_path %>

app/views/doggies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doggies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Temperment</th>
      <th>Funfact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doggies.each do |doggy| %>
      <tr>
        <td><%= doggy.name %></td>
        <td><%= doggy.breed %></td>
        <td><%= doggy.age %></td>
        <td><%= doggy.temperment %></td>
        <td><%= doggy.FunFact %></td>
        <td><%= link_to 'Show', doggy %></td>
        <td><%= link_to 'Edit', edit_doggy_path(doggy) %></td>
        <td><%= link_to 'Destroy', doggy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doggy', new_doggy_path %>

app/views/doggies/new.html.erb
<h1>New Doggy</h1>

<%= render 'form' %>

<%= link_to 'Back', doggies_path %>

app/views/doggies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doggy.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @doggy.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @doggy.age %>
</p>

<p>
  <strong>Temperment:</strong>
  <%= @doggy.temperment %>
</p>

<p>
  <strong>Funfact:</strong>
  <%= @doggy.FunFact %>
</p>

<%= link_to 'Edit', edit_doggy_path(@doggy) %> |
<%= link_to 'Back', doggies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waggr20</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
          	<%= yield %>
          </div>
            <h1 class="cover-heading">Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">Learn more</a>
            </p>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>